import "package:freezed_annotation/freezed_annotation.dart";
import "package:inventory_v1/core/util/util.dart";
import "package:inventory_v1/domain/entities/part/part_entity.dart";

// required: associates our `part_model.dart` with the code generated by Freezed
part 'part_model.freezed.dart';
// optional: Since our Part class is serializable, we must add this line.
// But if Part was not serializable, we could skip it.
part 'part_model.g.dart';
//responsible fot data structure conversion between part entities and part models.
part 'adapter.dart';

///Part Model. Represents a part stored within the database inventory
@freezed
class Part extends PartEntity with _$Part {
  ///Constructor
  ///accepts a [name]
  ///           [nsn]
  ///           [partNumber]
  ///           [location]
  ///           [quantity]
  ///           [requisitionPoint]
  ///           [requisitionQuantity]
  ///           [serialNumber]
  ///           [unitOfIssue]
  factory Part({
    required int index,
    @Default('unknown_part') String name,
    @Default('unknown_part') String nsn,
    @Default('unknown_part') String partNumber,
    @Default('unknown_part') String location,
    @Default(-1) int quantity,
    @Default(-1) int requisitionPoint,
    @Default(-1) int requisitionQuantity,
    @Default('N/A') String serialNumber,
    @Default(UnitOfIssue.NOT_SPECIFIED) UnitOfIssue unitOfIssue,
  }) = _PartModel;

  factory Part.fromJson(Map<String, dynamic> json) => _$PartFromJson(json);
}
